### ISSUE TITLE
Support for Rethinking Voxels?

### ISSUE THREAD

**Issue by Entropy159** [EuphoriaPatches/EuphoriaPatcher#6]
It would be amazing if you could add these patches (except for colored lighting) to Rethinking Voxels too. I personally love the blocklight shadows and volumetric lighting that Rethinking Voxels has, but I also like some features of Euphoria Patches.

**Comment by SpacEagle17** [comment]
It's not as straightforward as one might think and it's less likely to happen in the future with each passing update.
Though Complementary with 5.2 also has Voxelized colored lighting, so the only difference is rethinking voxels having block shadows coming from light sources

**Comment by Karpatok9089** [comment]
It would be nice to happen, because Rethinking Voxels has some features other than Block shadows that Euphoria Patches doesn't have like interactive water waves, world-space reflections, etc. The biggest problem is that rethinking voxels has an almost entirely modified lighting program, so it would require to rewrite Euphoria Patches in order to work with Rethinking Voxels. And it would also come with intense lag. (RV or EP already gets me about 50 FPS on my computer on max settings)
